name: Docker Image CI AnalizaGarantii

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag analiza_garantii
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
        
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Build image
      uses: docker/build-push-action@v2
      with:
          tags: ${{ steps.docker_meta.outputs.tags }} # gets tags from Docker_meta action
          file: ./Dockerfile
          
                
    - name: Push image
      uses: docker/build-push-action@v2
      with:
          push: true
          tags: ghcr.io/fizic37/AnalizaGarantii:latest  #${{ steps.docker_meta.outputs.tags }}
          file: ./Dockerfile
